services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=crud_user_db
      - MYSQL_ROOT_PASSWORD=1234
volumes:
  mysql-volume:
